@jiraSiteUrl = https://your-domain.atlassian.net
@jiraEmail = user@example.com
@jiraApiToken = replace_me
@epicKey = EXAMPLE-1

### REST: Get all issues for an epic
POST {{jiraSiteUrl}}/rest/api/3/search/jql
Authorization: Basic {{jiraEmail}} {{jiraApiToken}}
Accept: application/json
Content-Type: application/json

{
  "jql": "parent = {{epicKey}} ORDER BY created ASC",
  "fields": [
    "summary",
    "status",
    "issuetype",
    "parent"
  ],
  "maxResults": 50
}
